### ISSUE TITLE
Need a fix for Switch Pro Controllers

### ISSUE THREAD

**Issue by R2MGaming** [SortaCore/SDLJoystick-priv#1]
![IMG_20210823_135819](https://user-images.githubusercontent.com/65870862/130502997-905df934-cf84-485c-b0c1-fac83ee83550.jpg)
![Proof Clickteam](https://user-images.githubusercontent.com/65870862/130503066-b381db66-0a48-4e99-95b3-01923da0777e.png)
![IMG_20210823_135801](https://user-images.githubusercontent.com/65870862/130503090-a9fef6ab-2508-407f-bed7-c16baef15922.jpg)

I tried this with my Switch Pro Controller with the SDL Joystick Object in Fusion 2.5, and the problem with this issue is that it just freezes when you load the Switch Pro Conroller via either PC bluetooth or wired.

**Comment by SortaCore** [comment]
I'm seeing:
* If plugged in on app boot, works fine
* If plugged in while app is running, the example app runs normally, but the SDL expressions are frozen for a second or so, and back to normal for half a second
* If unplugged while app is running, app freezes (Not Responding)

Are you getting the same results?

I see SDL was [updated to 2.0.16](https://github.com/libsdl-org/SDL/releases/tag/release-2.0.16) with some changes to SDL, so since this ext uses 2.0.12, I'll update the version and see if that fixes it.

**Comment by R2MGaming** [comment]
Yes. I have tried it before, and it gives the same issue. And yes, that would be nice to have it updated please.

**Comment by SortaCore** [comment]
2.0.16 update appears to have the same problem, so looking more into it.

**Comment by R2MGaming** [comment]
I know it's been a while, but SDL updated to 2.0.20 so I'm not sure if it'll work, but can you try?

**Comment by SortaCore** [comment]
Fixed in [build 9](https://github.com/SortaCore/SDLJoystick-priv/commit/da83b6dc61b7b7d7843b2e9dead4068434784f30), was a missing SDL_TIMER in CMake, making timeouts not work - and for some reason, SDL ignored the error return from the time functions.
